### ISSUE TITLE
Delete Message Popup Is Non-Interactive

### ISSUE THREAD

**Issue by entropylaw** [ppfeufer/aa-forum#6] opened 2021-06-19 16:58 UTC
### aa-forum==0.0.1a9
When you click delete while viewing a post. It seems like the pop up dialog creates an invisible blank
sheet over the view that doesn't all you you to click on anything.

![brave_LUE6hytFoI](https://user-images.githubusercontent.com/28905617/122649803-51a0f500-d0f5-11eb-8158-b23644dcfee0.png)

When I inspect the browser and delete this element, I regain ability to click on the buttons

```
<div tabindex="-1" class="aa-forum-lightbox-modal modal fade __web-inspector-hide-shortcut__" id="lightboxModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal">×</button>

                </div>

                <div class="modal-body"></div>

                <div class="modal-footer">
                    <button class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
```

**Comment by ppfeufer** [comment] 2021-06-19 17:43
Which version you are running?

**Comment by entropylaw** [comment] 2021-06-19 17:54
Sorry, knew I forgot something.
`aa-forum==0.0.1a9`

**Comment by ppfeufer** [comment] 2021-06-19 18:02
That behaviour has actually been fixed in alpha-6 » https://github.com/ppfeufer/aa-forum/releases/tag/v0.0.1-alpha.6
There was an issue with the lightbox script and modals. And according to the HTML you posted, it seems there is still some interference for you.

I can't reproduce it on my end, unfortunately. What you can try is, clear your browser cache.

**Comment by ppfeufer** [comment] 2021-06-28 21:06
Since this is to 99.99999% a cache issue, I'm closing this one ...

**Closed by ppfeufer** 2021-06-28 21:06 UTC
